jobs:
  # Connect CI to the pipelines.
  # See: http://docs.shippable.com/tutorials/pipelines/connectingCiPipelines/
  - name: zipcode_runCI
    type: runCI
    # Specify resources (service images) updated by CI
    steps:
      - IN: zipcode_git
      - IN: kanister-dockerhub
      - IN:  zipcode-k8s-cfg
      - OUT: zipcode-img